name: checkout
on: [push]

jobs:
    checkout-list-files:
        runs-on: ubuntu-latest
        steps:
            - name: list files before git fetch
              run: ls -a
            - name: fetch the repo
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: list files after fetch
              run: ls -a