name: checkout-actions
on: [push]

jobs:
    checkout-actions-list-files:
        runs-on: ubuntu-latest
        steps:
            - name: list files before git fetch
              run: ls -a
            - name: checkout actions
              uses: actions/checkout@v3
            - name: list files after fetch
              run: ls -a