name: pr-comment
on:
    pull_request_target:
        types: [opened]

jobs:
    prc-comment:
        runs-on: ubuntu-latest
        steps:
            - name: comment on PRs
              uses: actions/github-script@v6
              with:
                script: | 
                    github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                        body: 'thanks for contributing'
                    })

